spring.mongodb.uri=${MONGODB_URL}
spring.mongodb.database=${REA_DATABASE}

REGISTERED_EMAIL_ADDRESS_FILING_DESCRIPTION_IDENTIFIER=**Registered Email Address** submission made
REGISTERED_EMAIL_ADDRESS_FILING_DESCRIPTION=Registered Email Address made on {registration date}
REGISTERED_EMAIL_ADDRESS_UPDATE_FILING_DESCRIPTION=Registered Email Address update made {date}

# may be overridden using envvar ALLOWED_COMPANY_STATUSES and ALLOWED_COMPANY_TYPES
allowed.company.statuses = active, liquidation, receivership, voluntary-agreement, insolvency-proceedings, administration
allowed.company.types = private-unlimited, ltd, plc, private-limited-guarant-nsc-limited-exemption, private-limited-guarant-nsc, private-unlimited-nsc, private-limited-shares-section-30-exemption, llp


management.endpoints.access.default=read_only
management.endpoints.web.base-path=
management.endpoints.web.path-mapping.health=/registered-email-address/healthcheck
management.endpoint.health.show-details=never
management.endpoints.web.exposure.include=health
management.opentelemetry.enabled=${OTEL_LOG_ENABLED:false}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics
